services:
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend/src/:/app/src

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volume:
      - ./frontend/src/:/app/src/
