services:
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volume:
      - ./frontend/src/:/app/src/
    depends_on: 
      backend:
        condition: service_healthy
        
  backend:
    build: ./backend
    ports:
      - 3000:3000
    volumes:
      - ./backend/src/:/app/src/
    healthcheck:
      test:
        [
          "CMD-SHELL", 
          'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend:3000'' --data ''{"query":"query" {__typename}"}'' || exit 1', 
        ]

  database:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
    environnement:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABSE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - ./database:/var/lib/prostgresql/data
