GET http://localhost:3000/tags

###

POST http://localhost:3000/tags
Content-Type:  application/json 

{
    "title": "the fourth one"
}

###

PUT http://localhost:3000/tags/4
Content-Type: application/json

{
    "title": "modified title"
}

###

DELETE http://localhost:3000/tags/2
Content-Type: application/json
